locations:
  lobby:
    lobbyworld: "lobby" #Mundo
    coordX: 0 #Coordenada X
    coordY: 90 #Coordenada Y
    coordZ: 0 #Coordenada Z
    pitch: 0 #Rotacion X
    yaw: 0 #Rotacion Y
antiblockprevent:
  protectedworld: "" #Mundo
  message: "" #Mensaje
modalitymenu:
  item: "NETHER_STAR" #Item
  hotbar: 4 #Ubicacion en la HOTBAR
messages:
  prefix: "&7[&3BahiaMinecraft&7] "